spring:
  application:
    name: bank
  mongodb:
    uri: mongodb://localhost:27017/exp_bank
server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    shutdown:
      access: unrestricted
  info:
    env:
      enabled: true


info:
  app:
    name: "bank"
    description: "experiment microservice with a dummy topic bank"
    version: "v1"
    precaution: "don't add in your main project, this is just for learning purpose"

