spring:
  application:
    name: bank
  mongodb:
    uri: mongodb://localhost:27017/exp_bank
server:
  port: 8082

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/
