spring:
  application:
    name:  user
  mongodb:
    uri: mongodb://localhost:27017/exp_User

server:
  port: 8081

eureka:
  instance:
    preferIpAddress: true
  client:
    fetchRegistry: true
    registerWithEureka: true
    serviceUrl:
      defaultZone: http://localhost:9001/eureka/